#!/usr/bin/env python3
r"""
Extract filament usage from an OrcaSlicer/Bambu-style 3MF.

The script checks three sources independently:
1. Embedded plate G-code comments (`Metadata/plate_1.gcode`)
2. `Metadata/slice_info.config`
3. `python -m octoprint analysis gcode ...` on the embedded G-code

Example:
    python orca_3mf_filament_report.py "C:\Users\This PC\Downloads\output.3mf"
    python orca_3mf_filament_report.py "https://example.com/output.3mf" --density 1.24
"""

from __future__ import annotations

import argparse
import io
import json
import math
import os
import re
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request
import zipfile
from collections import defaultdict
from pathlib import Path
from typing import Any
from xml.etree import ElementTree


DEFAULT_DENSITY_BY_TYPE = {
    "PLA": 1.24,
    "PLA+": 1.24,
    "PETG": 1.27,
    "ABS": 1.04,
    "ASA": 1.07,
    "TPU": 1.21,
    "PA": 1.14,
    "NYLON": 1.14,
    "PC": 1.20,
}


def _looks_like_url(value: str) -> bool:
    parsed = urllib.parse.urlparse(value)
    return parsed.scheme in {"http", "https"}


def load_input_bytes(source: str) -> tuple[bytes, str]:
    if _looks_like_url(source):
        with urllib.request.urlopen(source) as response:
            return response.read(), source
    path = Path(source).expanduser().resolve()
    return path.read_bytes(), str(path)


def find_plate_gcode_name(names: list[str]) -> str | None:
    for name in names:
        if re.fullmatch(r"Metadata/plate_\d+\.gcode", name):
            return name
    return None


def find_member(names: list[str], exact_name: str) -> str | None:
    for name in names:
        if name == exact_name:
            return name
    return None


def parse_float(text: str) -> float | None:
    try:
        return float(text)
    except (TypeError, ValueError):
        return None


def extract_gcode_stats(gcode_text: str) -> dict[str, Any]:
    stats: dict[str, Any] = {}
    patterns = {
        "filament_used_mm": r"^;\s*filament used \[mm\]\s*=\s*([0-9.]+)",
        "filament_used_cm3": r"^;\s*filament used \[cm3\]\s*=\s*([0-9.]+)",
        "filament_density_header": r"^;\s*filament_density:\s*([0-9.]+)",
        "filament_density_config": r"^;\s*filament_density\s*=\s*([0-9.]+)",
        "filament_diameter_mm": r"^;\s*filament_diameter:\s*([0-9.]+)",
        "filament_diameter_config_mm": r"^;\s*filament_diameter\s*=\s*([0-9.]+)",
        "generated_by": r"^;\s*generated by\s+(.+)$",
        "model_printing_time": r"^;\s*model printing time:\s*(.+)$",
        "total_layers": r"^;\s*total layer number:\s*([0-9.]+)",
    }
    for line in gcode_text.splitlines():
        for key, pattern in patterns.items():
            match = re.match(pattern, line)
            if match and key not in stats:
                value = match.group(1).strip()
                stats[key] = parse_float(value) if re.fullmatch(r"[0-9.]+", value) else value
    density = stats.get("filament_density_header") or stats.get("filament_density_config")
    diameter = stats.get("filament_diameter_mm") or stats.get("filament_diameter_config_mm")
    if density is not None:
        stats["filament_density_g_cm3"] = density
    if diameter is not None:
        stats["filament_diameter_mm"] = diameter
    return stats


def split_comment_payload(value: str | None) -> list[str]:
    if not value:
        return []
    return [item.strip() for item in value.split(";")]


def extract_gcode_header_lists(gcode_text: str) -> dict[str, list[str]]:
    result: dict[str, list[str]] = {}
    patterns = {
        "filament_colour": r"^;\s*filament_colour\s*=\s*(.+)$",
        "filament_type": r"^;\s*filament_type\s*=\s*(.+)$",
        "filament_density": r"^;\s*filament_density\s*=\s*(.+)$",
        "filament_diameter": r"^;\s*filament_diameter\s*=\s*(.+)$",
    }
    for line in gcode_text.splitlines():
        for key, pattern in patterns.items():
            match = re.match(pattern, line)
            if match and key not in result:
                result[key] = split_comment_payload(match.group(1).strip())
    return result


def parse_tool_id(line: str) -> int | None:
    match = re.match(r"^T(-?\d+)\s*$", line.strip())
    if not match:
        return None
    return int(match.group(1))


def parse_gcode_parameters(code: str) -> dict[str, float]:
    params: dict[str, float] = {}
    for key, value in re.findall(r"([A-Za-z])([+-]?(?:\d+(?:\.\d*)?|\.\d+))", code):
        try:
            params[key.upper()] = float(value)
        except ValueError:
            continue
    return params


def is_printable_tool(tool_id: int | None, declared_tool_count: int) -> bool:
    if tool_id is None:
        return False
    if declared_tool_count > 0:
        return 0 <= tool_id < declared_tool_count
    return 0 <= tool_id < 32


def analyze_gcode_per_filament(
    gcode_text: str,
    diameter_mm: float | None,
    density_by_tool: dict[int, float | None],
    declared_tool_count: int,
) -> dict[str, Any]:
    extrusion_mode_absolute = True
    current_tool: int | None = None
    last_e_global = 0.0
    last_e_by_tool: dict[int, float] = defaultdict(float)
    total_positive_e_by_tool: dict[int, float] = defaultdict(float)
    tool_change_count = 0
    ignored_tool_changes: list[int] = []

    for raw_line in gcode_text.splitlines():
        line = raw_line.split(";", 1)[0].strip()
        if not line:
            continue

        tool_id = parse_tool_id(line)
        if tool_id is not None:
            if current_tool != tool_id:
                tool_change_count += 1
            current_tool = tool_id
            if not is_printable_tool(tool_id, declared_tool_count):
                ignored_tool_changes.append(tool_id)
            continue

        code = line.split(None, 1)[0].upper()
        params = parse_gcode_parameters(line)

        if code == "M82":
            extrusion_mode_absolute = True
            continue
        if code == "M83":
            extrusion_mode_absolute = False
            continue
        if code == "G92":
            if "E" in params:
                if extrusion_mode_absolute and current_tool is not None and is_printable_tool(current_tool, declared_tool_count):
                    last_e_by_tool[int(current_tool)] = params["E"]
                last_e_global = params["E"]
            continue

        if code not in {"G0", "G1", "G2", "G3"}:
            continue
        if "E" not in params:
            continue

        delta_e = 0.0
        if extrusion_mode_absolute:
            if current_tool is not None and is_printable_tool(current_tool, declared_tool_count):
                delta_e = params["E"] - last_e_by_tool[int(current_tool)]
                last_e_by_tool[int(current_tool)] = params["E"]
            else:
                delta_e = params["E"] - last_e_global
            last_e_global = params["E"]
        else:
            delta_e = params["E"]

        if delta_e <= 0:
            continue
        if not is_printable_tool(current_tool, declared_tool_count):
            continue

        total_positive_e_by_tool[int(current_tool)] += delta_e

    per_filament: list[dict[str, Any]] = []
    total_length_mm = 0.0
    total_volume_cm3 = 0.0
    total_grams = 0.0
    grams_complete = True
    for tool_id in sorted(total_positive_e_by_tool):
        length_mm = total_positive_e_by_tool[tool_id]
        length_m = length_mm / 1000.0
        volume_cm3 = None
        grams = None
        if diameter_mm is not None:
            volume_cm3 = (length_mm * math.pi * (diameter_mm / 2.0) ** 2) / 1000.0
            density = density_by_tool.get(tool_id)
            if density is not None:
                grams = volume_cm3 * density
        total_length_mm += length_mm
        if volume_cm3 is not None:
            total_volume_cm3 += volume_cm3
        if grams is not None:
            total_grams += grams
        else:
            grams_complete = False
        per_filament.append(
            {
                "tool": tool_id,
                "length_mm": length_mm,
                "length_m": length_m,
                "volume_cm3": volume_cm3,
                "grams": grams,
            }
        )

    return {
        "per_filament": per_filament,
        "total_length_mm": total_length_mm,
        "total_length_m": total_length_mm / 1000.0,
        "total_volume_cm3": total_volume_cm3 if diameter_mm is not None else None,
        "total_grams": total_grams if grams_complete else None,
        "tool_change_count": tool_change_count,
        "ignored_tool_changes": sorted(set(ignored_tool_changes)),
    }


def parse_slice_info(xml_bytes: bytes) -> dict[str, Any]:
    root = ElementTree.fromstring(xml_bytes.decode("utf-8", errors="replace"))
    result: dict[str, Any] = {"header": {}, "plate": {}, "filament": None, "filaments": [], "layer_filament_lists": []}

    for item in root.findall("./header/header_item"):
        key = item.attrib.get("key")
        value = item.attrib.get("value")
        if key:
            result["header"][key] = value

    plate = root.find("./plate")
    if plate is None:
        return result

    for metadata in plate.findall("./metadata"):
        key = metadata.attrib.get("key")
        value = metadata.attrib.get("value")
        if key:
            result["plate"][key] = value

    filament = plate.find("./filament")
    if filament is not None:
        result["filament"] = dict(filament.attrib)
    result["filaments"] = [dict(node.attrib) for node in plate.findall("./filament")]

    obj = plate.find("./object")
    if obj is not None:
        result["object"] = dict(obj.attrib)

    result["layer_filament_lists"] = [dict(node.attrib) for node in plate.findall("./layer_filament_lists/layer_filament_list")]

    return result


def density_from_sources(
    args_density: float | None,
    gcode_stats: dict[str, Any],
    slice_info: dict[str, Any],
) -> tuple[float | None, str | None]:
    if args_density is not None:
        return args_density, "cli_override"

    density = gcode_stats.get("filament_density_g_cm3")
    if isinstance(density, (int, float)) and density > 0:
        return float(density), "embedded_gcode"

    filament = slice_info.get("filament") or {}
    filament_type = (filament.get("type") or "").upper()
    if filament_type in DEFAULT_DENSITY_BY_TYPE:
        return DEFAULT_DENSITY_BY_TYPE[filament_type], f"default_for_{filament_type}"

    return None, None


def grams_from_volume_cm3(volume_cm3: float | None, density_g_cm3: float | None) -> float | None:
    if volume_cm3 is None or density_g_cm3 is None:
        return None
    return volume_cm3 * density_g_cm3


def grams_from_length_m(length_m: float | None, diameter_mm: float | None, density_g_cm3: float | None) -> float | None:
    if length_m is None or diameter_mm is None or density_g_cm3 is None:
        return None
    return length_m * math.pi * (diameter_mm / 2.0) ** 2 * density_g_cm3


def run_octoprint_analysis(gcode_bytes: bytes) -> dict[str, Any]:
    with tempfile.TemporaryDirectory(prefix="orca_gcode_") as temp_dir:
        gcode_path = Path(temp_dir) / "plate_1.gcode"
        gcode_path.write_bytes(gcode_bytes)
        completed = subprocess.run(
            [sys.executable, "-m", "octoprint", "analysis", "gcode", str(gcode_path)],
            capture_output=True,
            text=True,
            check=False,
        )
        output = completed.stdout + ("\n" + completed.stderr if completed.stderr else "")
        result: dict[str, Any] = {
            "command_ok": completed.returncode == 0,
            "returncode": completed.returncode,
            "raw_output": output.strip(),
        }
        match = re.search(r"extrusion_length:\s*-\s*([0-9.]+)", output)
        if match:
            result["extrusion_length_mm"] = float(match.group(1))
        match = re.search(r"extrusion_volume:\s*-\s*([0-9.]+)", output)
        if match:
            result["extrusion_volume_cm3"] = float(match.group(1))
        match = re.search(r"total_time:\s*([0-9.]+)", output)
        if match:
            result["total_time_min"] = float(match.group(1))
        return result


def build_report(source: str, density_override: float | None) -> dict[str, Any]:
    data, resolved_source = load_input_bytes(source)
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        names = archive.namelist()
        gcode_name = find_plate_gcode_name(names)
        slice_info_name = find_member(names, "Metadata/slice_info.config")
        filament_sequence_name = find_member(names, "Metadata/filament_sequence.json")

        if not gcode_name:
            raise FileNotFoundError("Could not find Metadata/plate_*.gcode in the 3MF package.")
        if not slice_info_name:
            raise FileNotFoundError("Could not find Metadata/slice_info.config in the 3MF package.")

        gcode_bytes = archive.read(gcode_name)
        gcode_text = gcode_bytes.decode("utf-8", errors="replace")
        gcode_stats = extract_gcode_stats(gcode_text)
        gcode_header_lists = extract_gcode_header_lists(gcode_text)
        slice_info = parse_slice_info(archive.read(slice_info_name))
        filament_sequence = None
        if filament_sequence_name:
            filament_sequence = json.loads(archive.read(filament_sequence_name).decode("utf-8", errors="replace"))

    filament = slice_info.get("filament") or {}
    filaments = slice_info.get("filaments") or []
    length_m_from_slice_info = parse_float(filament.get("used_m"))
    grams_from_slice_info = parse_float(filament.get("used_g"))
    density_g_cm3, density_source = density_from_sources(density_override, gcode_stats, slice_info)

    gcode_length_mm = gcode_stats.get("filament_used_mm")
    gcode_volume_cm3 = gcode_stats.get("filament_used_cm3")
    gcode_length_m = gcode_length_mm / 1000.0 if isinstance(gcode_length_mm, (int, float)) else None
    gcode_diameter_mm = gcode_stats.get("filament_diameter_mm")
    grams_from_gcode_volume = grams_from_volume_cm3(gcode_volume_cm3, density_g_cm3)
    grams_from_gcode_length = grams_from_length_m(gcode_length_m, gcode_diameter_mm, density_g_cm3)

    octoprint = run_octoprint_analysis(gcode_bytes)
    octo_length_mm = octoprint.get("extrusion_length_mm")
    octo_length_m = octo_length_mm / 1000.0 if isinstance(octo_length_mm, (int, float)) else None
    octo_volume_cm3 = octoprint.get("extrusion_volume_cm3")
    octo_grams = grams_from_volume_cm3(octo_volume_cm3, density_g_cm3)

    used_filaments: list[dict[str, Any]] = []
    for index, entry in enumerate(filaments):
        used_m = parse_float(entry.get("used_m"))
        used_g = parse_float(entry.get("used_g"))
        used_for_object = (entry.get("used_for_object") or "").lower() == "true"
        used_for_support = (entry.get("used_for_support") or "").lower() == "true"
        is_used = bool((used_m and used_m > 0) or used_for_object or used_for_support)
        used_filaments.append(
            {
                "slice_index": index,
                "id": entry.get("id"),
                "type": entry.get("type"),
                "color": entry.get("color"),
                "nozzle_diameter": entry.get("nozzle_diameter"),
                "volume_type": entry.get("volume_type"),
                "used_m": used_m,
                "used_g": used_g,
                "used_for_object": used_for_object,
                "used_for_support": used_for_support,
                "is_used": is_used,
            }
        )

    declared_tool_count = max(
        len(gcode_header_lists.get("filament_type", [])),
        len(gcode_header_lists.get("filament_colour", [])),
        len(used_filaments),
    )
    density_values = [parse_float(value) for value in gcode_header_lists.get("filament_density", [])]
    diameter_values = [parse_float(value) for value in gcode_header_lists.get("filament_diameter", [])]
    density_by_tool: dict[int, float | None] = {}
    for tool_id in range(declared_tool_count):
        density_candidate = density_values[tool_id] if tool_id < len(density_values) else None
        if density_candidate is None or density_candidate <= 0:
            density_candidate = density_g_cm3
        density_by_tool[tool_id] = density_candidate
    manual_gcode_analysis = analyze_gcode_per_filament(
        gcode_text=gcode_text,
        diameter_mm=(diameter_values[0] if diameter_values and diameter_values[0] else gcode_diameter_mm),
        density_by_tool=density_by_tool,
        declared_tool_count=declared_tool_count,
    )
    for index, entry in enumerate(manual_gcode_analysis["per_filament"]):
        if index < len(gcode_header_lists.get("filament_type", [])):
            entry["declared_type"] = gcode_header_lists["filament_type"][index]
        if index < len(gcode_header_lists.get("filament_colour", [])):
            entry["declared_color"] = gcode_header_lists["filament_colour"][index]
        if index < len(used_filaments):
            entry["slice_info_used_m"] = used_filaments[index].get("used_m")
            entry["slice_info_used_g"] = used_filaments[index].get("used_g")

    return {
        "source": resolved_source,
        "gcode_member": gcode_name,
        "density_g_cm3_used_for_calculations": density_g_cm3,
        "density_source": density_source,
        "embedded_gcode_stats": {
            "length_mm": gcode_length_mm,
            "length_m": gcode_length_m,
            "volume_cm3": gcode_volume_cm3,
            "diameter_mm": gcode_diameter_mm,
            "density_g_cm3_reported": gcode_stats.get("filament_density_g_cm3"),
            "grams_from_volume": grams_from_gcode_volume,
            "grams_from_length": grams_from_gcode_length,
            "generated_by": gcode_stats.get("generated_by"),
            "model_printing_time": gcode_stats.get("model_printing_time"),
            "total_layers": gcode_stats.get("total_layers"),
        },
        "slice_info_stats": {
            "used_m": length_m_from_slice_info,
            "used_g": grams_from_slice_info,
            "filament_type": filament.get("type"),
            "filament_color": filament.get("color"),
            "nozzle_diameter": filament.get("nozzle_diameter"),
            "filaments": used_filaments,
            "layer_filament_lists": slice_info.get("layer_filament_lists"),
        },
        "filament_sequence": filament_sequence,
        "manual_gcode_analysis": manual_gcode_analysis,
        "octoprint_analysis": {
            "length_mm": octo_length_mm,
            "length_m": octo_length_m,
            "volume_cm3": octo_volume_cm3,
            "grams_from_volume": octo_grams,
            "command_ok": octoprint.get("command_ok"),
            "returncode": octoprint.get("returncode"),
            "per_filament_supported_reliably": False,
            "per_filament_note": (
                "OctoPrint analysis is used here as the trust source for total extrusion only. "
                "Bambu/Orca G-code uses nonstandard tool selections like T1000/T1100/T255, "
                "so per-filament splits are not reliably available from OctoPrint."
            ),
        },
    }


def print_human_report(report: dict[str, Any]) -> None:
    print(f"Source: {report['source']}")
    print(f"Embedded gcode member: {report['gcode_member']}")
    if report["density_g_cm3_used_for_calculations"] is not None:
        print(
            f"Density used for gram calculations: "
            f"{report['density_g_cm3_used_for_calculations']} g/cm^3 "
            f"({report['density_source']})"
        )
    else:
        print("Density used for gram calculations: unavailable")

    print("\nEmbedded G-code stats")
    embedded = report["embedded_gcode_stats"]
    for key in ("length_mm", "length_m", "volume_cm3", "diameter_mm", "density_g_cm3_reported", "grams_from_volume", "grams_from_length"):
        print(f"  {key}: {embedded.get(key)}")

    print("\nSlice info stats")
    slice_info = report["slice_info_stats"]
    for key in ("used_m", "used_g", "filament_type", "filament_color", "nozzle_diameter"):
        print(f"  {key}: {slice_info.get(key)}")
    if slice_info.get("filaments"):
        print("  filaments:")
        for filament in slice_info["filaments"]:
            print(
                "    "
                + json.dumps(
                    filament,
                    separators=(", ", ": "),
                )
            )
    if slice_info.get("layer_filament_lists"):
        print("  layer_filament_lists:")
        for layer_list in slice_info["layer_filament_lists"]:
            print("    " + json.dumps(layer_list, separators=(", ", ": ")))

    print("\nManual G-code analysis")
    manual = report["manual_gcode_analysis"]
    print(f"  tool_change_count: {manual.get('tool_change_count')}")
    print(f"  ignored_tool_changes: {manual.get('ignored_tool_changes')}")
    print(f"  total_length_mm: {manual.get('total_length_mm')}")
    print(f"  total_length_m: {manual.get('total_length_m')}")
    print(f"  total_volume_cm3: {manual.get('total_volume_cm3')}")
    print(f"  total_grams: {manual.get('total_grams')}")
    for filament in manual.get("per_filament", []):
        print("  filament: " + json.dumps(filament, separators=(", ", ": ")))

    print("\nOctoPrint analysis")
    octo = report["octoprint_analysis"]
    for key in (
        "length_mm",
        "length_m",
        "volume_cm3",
        "grams_from_volume",
        "command_ok",
        "returncode",
        "per_filament_supported_reliably",
    ):
        print(f"  {key}: {octo.get(key)}")
    print(f"  per_filament_note: {octo.get('per_filament_note')}")

    if report.get("filament_sequence") is not None:
        print("\nFilament sequence")
        print(json.dumps(report["filament_sequence"], indent=2))


def main() -> int:
    parser = argparse.ArgumentParser(description="Inspect Orca/Bambu 3MF filament metadata.")
    parser.add_argument("source", help="HTTP(S) URL or local path to a 3MF file.")
    parser.add_argument(
        "--density",
        type=float,
        help="Override filament density in g/cm^3 for gram calculations.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print the final report as JSON.",
    )
    args = parser.parse_args()

    report = build_report(args.source, args.density)
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print_human_report(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
